version: '3.8'

services:
  portfolio:
    build: .
    ports:
      - "3000:80"
    container_name: portfolio-website
    restart: unless-stopped
    volumes:
      - .:/usr/share/nginx/html:ro
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
